version: '3.7'

networks:
  smartmes:
    driver: bridge

services:
  db:
    image: mysql:8.0.20
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: db_smartmes
      TZ: America/Belem
    networks:
      - smartmes
    volumes:
      - "./data:/docker-entrypoint-initdb.d/"

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: smartmes-manufacturing
    container_name: smartmes-manufacturing
    networks:
      - smartmes
    environment:
      - JAVA_OPTS=-Dspring.profiles.active=default
      - DB_HOST=172.30.0.2 # caso não subir a aplicação, alterar o host para o IP do container mysql
    ports:
      - "8080:8080"
    privileged: true
    depends_on:
      - db
